# Generated by Django 4.2.13 on 2026-05-15 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='customer_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
