# Generated by Django 4.2.13 on 2026-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('Food & Beverages', 'Food & Beverages'), ('Fresh Vegetables', 'Fresh Vegetables'), ('Agriculture & Grains', 'Agriculture & Grains'), ('Clothes & Textiles', 'Clothes & Textiles'), ('Electronics & Mobile', 'Electronics & Mobile'), ('Home & Kitchen', 'Home & Kitchen'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Books & Stationery', 'Books & Stationery'), ('Toys & Games', 'Toys & Games'), ('Jewellery & Accessories', 'Jewellery & Accessories'), ('Hardware & Tools', 'Hardware & Tools'), ('Herbs & Ayurveda', 'Herbs & Ayurveda'), ('Dairy Products', 'Dairy Products'), ('Bakery & Sweets', 'Bakery & Sweets'), ('Art & Handicrafts', 'Art & Handicrafts'), ('General Store', 'General Store'), ('Auto Parts', 'Auto Parts'), ('Flowers & Plants', 'Flowers & Plants'), ('Footwear', 'Footwear'), ('Music & Instruments', 'Music & Instruments')], default='Food & Beverages', max_length=30),
        ),
    ]
